experiment_name: 'experiments' # Name of the experiment
experiment_dir: './experiments/'  # Directory to potentially save the model to

seed: 0 # Random seed
workers: 8 # Number of workers for data loading
save_model: True # Whether to save the model. Set to True for inspecting models post training [True, False]
train_only: False # Whether to train the model only and exit before performing interventions [True, False]
gpu: 0

logging:
  project: 'SCBM' # Name of the wandb project
  mode: 'offline' # Whether to log to wandb [online, offline, disabled]
  entity: "your_entity" # Your wandb entity